### ISSUE TITLE
Support for long

### ISSUE THREAD

**Issue by rapoth** [lemire/csharpewah#11]
I have a quick clarification question. Do you have any plans for supporting longs (e.g., bitmap.Set(long)) or perhaps an alternate implementation that supports long? 

Thank you!

**Comment by lemire** [comment]
Speaking for me personally? I do not. Sorry. :-(

**Comment by lemire** [comment]
I should qualify this statement by saying that there are 64-bit versions of Roaring bitmaps, and we have plans to support 64-bit integers in future formats. But I took your question as having to do with csharpewah and in that case, the answer is no. Of course, pull requests are invited.

**Comment by rapoth** [comment]
Thank you for your quick reply. I have two follow-up questions:

1. Can you comment on the work needed to support long in the current implementation? Are there any caveats based on your experience?
2. Could you please point me to the 64-bit version of Roaring bitmaps? I am looking at [roaring.h](https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/roaring.h#L229) but cannot find an add call that takes a long. Might be the case that I totally missed it. 

Thanks again!

**Comment by lemire** [comment]
> Also, I see the approach used is a map of bitmaps. Is this the suggested approach for supporting long even in say, EWAH?

It is difficult to reason in the abstract. Choosing the best data structure can only be done once you know the problem.

This being said, this is how we currently solve the problem, yes.

> As a final question, could you please point me towards your latest work evaluating EWAH vs Roaring performance and under what scenarios each should be used/avoided?

There is some discussion in the following paper: https://arxiv.org/abs/1603.06549

You may also enjoy this talk (in two parts):
- https://www.youtube.com/watch?v=ubykHUyNi_0
- https://www.youtube.com/watch?v=1QMgGxiCFWE

**Comment by rapoth** [comment]
Thank you for the pointers! The paper and your talks were an excellent resource!
